---
# File: playbooks/01_verify_connectivity.yml
# Purpose: Verify that Ansible can reach each device.

- name: Connectivity Check Playbook
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Ping all devices
      ios_command:
        commands:
          - ping 10.0.2.15
