---
- name: Verify Network Connectivity
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Ping Device
      ios_ping:
        dest: "{{ ansible_host }}"
      register: ping_result

    - name: Display Ping Results
      debug:
        var: ping_result
