---
- name: Verify device connectivity
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Check connectivity via ping
      ios_command:
        commands:
          - ping: 10.0.2.15
