---
- name: Basic configuration for router
  hosts: router
  gather_facts: false
  connection: local
  tasks:
    - name: Configure hostname
      become: yes
      become_method: enable
      ios_config:
        lines:
          - hostname R1

    - name: Configure Domain Name
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip domain-name ansible.com
          
    - name: Generate RSA Keys for SSH
      become: yes
      become_method: enable
      ios_config:
        lines:
          - crypto key generate rsa modules 1024
