---
- name: Basic configuration for routers
  hosts: Router
  gather_facts: false
  connection: local
  
  tasks:
    - name: Configure hostname
     

- name: Basic configuration for switches
  hosts: Switch
  gather_facts: false
  connection: local

  task: 
    - name: Configure 
      iso_command:
        commands:
          - hostname R1
          - ip domain-name cisco.com
          - line vty 0 24 
          - transport input ssh

