---
- name: Basic configuration for router
  hosts: Router
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Configure hostname
      become: yes
      become_method: enable
      ios_config:
        lines:
          - hostname R1

    - name: Configure Domain Name
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip domain-name ansible.com
          
    - name: Generate RSA Keys for SSH
      become: yes
      become_method: enable
      ios_config:
        lines:
          - crypto key generate rsa modulus 1024

    - name: enable ssh on vty lines
      become: yes
      become_method: enable
      ios_config:
        parents:
          - line vty 0 4
        lines:
          - transport input ssh
          - login local

- name: Basic configuration for Switch
  hosts: Switch
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Configure hostname
      become: yes
      become_method: enable
      ios_config:
        lines:
          - hostname S1

    - name: Configure Domain Name
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip domain-name ansible.com
          
    - name: Generate RSA Keys for SSH
      become: yes
      become_method: enable
      ios_config:
        lines:
          - crypto key generate rsa modulus 1024

    - name: enable ssh on vty lines
      become: yes
      become_method: enable
      ios_config:
        parents:
          - line vty 0 4
        lines:
          - transport input ssh
          - login local