---
- name: Basic configuration for routers and switches
  hosts: all
  gather_facts: false
  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}
        provider: "{{ cli }}"
    
    - name: Configure domain name
      ios_config:
        lines:
          - ip domain-name {{ domain_name }}
        provider: "{{ cli }}"

    - name: Enable SSH
      ios_config:
        lines:
          - ip ssh version 2
          - line vty 0 4
          - transport input ssh
        provider: "{{ cli }}"