---
- name: VLAN Configuration on Switches
  hosts: switches
  gather_facts: no

  vars:
    vlans:
      - id: 10
        name: VLAN10
      - id: 20
        name: VLAN20

  tasks:
    - name: Create VLANs on switches
      ansible.netcommon.cli_config:
        lines:
          - "vlan {{ item.id }}"
          - "name {{ item.name }}"
        match: none
      loop: "{{ vlans }}"
      register: vlan_config

    - name: Display configuration changes
      debug:
        var: vlan_config
