---
- name: VLAN Configuration on Switches
  hosts: Switch
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure vlan10
      become: yes
      become_method: enable
      ios_config:
        parents:
          - vlan 10
        lines:
          - name ManagementVlan
    
    - name: Configure vlan20
      become: yes
      become_method: enable
      ios_config:
        parents:
          - vlan 20
        lines:
          - name BallsVlan