---
- name: Backup running configuration from network devices
  hosts: all
  gather_facts: no

  vars:
    backup_path: "/backups/{{ inventory_hostname }}"

  tasks:
    - name: Create backup directory if not exists
      ansible.builtin.file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'

    - name: Back up running configuration
      ansible.netcommon.cli_command:
        command: "show running-config"
      register: running_config

    - name: Save running configuration to a file
      ansible.builtin.copy:
        content: "{{ running_config.stdout }}"
        dest: "{{ backup_path }}/running-config-{{ ansible_date_time.iso8601 }}.txt"
