---
- name: Save running-config to startup-config
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Save running-config to startup-config
      become: yes
      become_method: enable
      ios_config:
        save_when: always

    
